version: '3.9'

services:
  app:
    build:
      context: client
    image: client:1.0
    container_name: client-app
    ports:
      - '5000:5000'
    #env_file:
     # - './.env'
    networks:
      - mongo_network
    depends_on:
      - mongo

  backend:
    image: backend:1.0
    container_name: backend-app
    ports:
      - '5000:5000'
   # env_file:
      #- '.backend/.env'
    networks:
      - mongo_network
    depends_on:
      - mongo


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - database:/data/db
    networks:
      - mongo_network

volumes:
  database:

networks:
  mongo_network:
    driver: bridge